export const toolsConfig = [
  {
    id: "1",
    name: "Create/Update File",
    description: "Create a new file or update an existing file in the project",
    filename: "tool1_create_update_file.json",
    config: {
      type: "webhook",
      name: "create_or_update_file",
      description: "Create a new file or update an existing file in the project. Use this when the user wants to generate new code or modify existing code. Always provide complete, working code in the file_content parameter.",
      api_schema: {
        url: "https://code-easy-gamma.vercel.app/api/webhooks/elevenlabs",
        method: "POST",
        path_params_schema: [],
        query_params_schema: [],
        request_body_schema: {
          id: "body",
          type: "object",
          description: "The request body containing file action details",
          required: true,
          properties: [
            {
              id: "action_type",
              type: "string",
              description: "The action to perform. Must be either 'create' for new files or 'update' for existing files.",
              dynamic_variable: "",
              constant_value: "",
              value_type: "llm_prompt",
              required: true,
            },
            {
              id: "file_path",
              type: "string",
              description: "The file path relative to project root (e.g., 'src/components/Button.tsx', 'utils/helpers.js'). Always include the full path with file extension.",
              dynamic_variable: "",
              constant_value: "",
              value_type: "llm_prompt",
              required: true,
            },
            {
              id: "file_content",
              type: "string",
              description: "The complete file content including all code, imports, and comments. This must be the full, working code - not a snippet or partial code.",
              dynamic_variable: "",
              constant_value: "",
              value_type: "llm_prompt",
              required: true,
            },
            {
              id: "project_id",
              type: "string",
              description: "The project ID",
              dynamic_variable: "",
              constant_value: "68c9f40a002d5afe6b43",
              value_type: "constant",
              required: true,
            },
            {
              id: "description",
              type: "string",
              description: "Brief description of what the code does (optional)",
              dynamic_variable: "",
              constant_value: "",
              value_type: "llm_prompt",
              required: false,
            },
          ],
          dynamic_variable: "",
          constant_value: "",
          value_type: "llm_prompt",
        },
        request_headers: [],
        auth_connection: null,
      },
      response_timeout_secs: 30,
      assignments: [],
      disable_interruptions: false,
      force_pre_tool_speech: "auto",
      tool_call_sound: null,
      tool_call_sound_behavior: "auto",
      execution_mode: "immediate",
      dynamic_variables: {
        dynamic_variable_placeholders: {},
      },
    },
  },
  {
    id: "2",
    name: "Delete File",
    description: "Delete a file or folder from the project",
    filename: "tool2_delete_file.json",
    config: {
      type: "webhook",
      name: "delete_file",
      description: "Delete a file or folder from the project. Use this when the user wants to remove a file or clean up the project structure.",
      api_schema: {
        url: "https://code-easy-gamma.vercel.app/api/webhooks/elevenlabs",
        method: "POST",
        path_params_schema: [],
        query_params_schema: [],
        request_body_schema: {
          id: "body",
          type: "object",
          description: "The request body containing delete action details",
          required: true,
          properties: [
            {
              id: "action_type",
              type: "string",
              description: "The action type, always 'delete' for this tool",
              dynamic_variable: "",
              constant_value: "delete",
              value_type: "constant",
              required: true,
            },
            {
              id: "file_path",
              type: "string",
              description: "The file or folder path to delete (e.g., 'src/components/Button.tsx' or 'src/utils/'). If deleting a folder, set is_folder to true.",
              dynamic_variable: "",
              constant_value: "",
              value_type: "llm_prompt",
              required: true,
            },
            {
              id: "project_id",
              type: "string",
              description: "The project ID",
              dynamic_variable: "",
              constant_value: "68c9f40a002d5afe6b43",
              value_type: "constant",
              required: true,
            },
            {
              id: "is_folder",
              type: "boolean",
              description: "Set to true if deleting a folder, false if deleting a file. Defaults to false if not specified.",
              dynamic_variable: "",
              constant_value: "",
              value_type: "llm_prompt",
              required: false,
            },
          ],
          dynamic_variable: "",
          constant_value: "",
          value_type: "llm_prompt",
        },
        request_headers: [],
        auth_connection: null,
      },
      response_timeout_secs: 20,
      assignments: [],
      disable_interruptions: false,
      force_pre_tool_speech: "auto",
      tool_call_sound: null,
      tool_call_sound_behavior: "auto",
      execution_mode: "immediate",
      dynamic_variables: {
        dynamic_variable_placeholders: {},
      },
    },
  },
  {
    id: "3",
    name: "Rename File",
    description: "Rename a file or folder in the project",
    filename: "tool3_rename_file.json",
    config: {
      type: "webhook",
      name: "rename_file",
      description: "Rename a file or folder in the project. Use this when the user wants to change a file name or reorganize the project structure.",
      api_schema: {
        url: "https://code-easy-gamma.vercel.app/api/webhooks/elevenlabs",
        method: "POST",
        path_params_schema: [],
        query_params_schema: [],
        request_body_schema: {
          id: "body",
          type: "object",
          description: "The request body containing rename action details",
          required: true,
          properties: [
            {
              id: "action_type",
              type: "string",
              description: "The action type, always 'rename' for this tool",
              dynamic_variable: "",
              constant_value: "rename",
              value_type: "constant",
              required: true,
            },
            {
              id: "file_path",
              type: "string",
              description: "The current file or folder path (e.g., 'src/components/OldButton.tsx')",
              dynamic_variable: "",
              constant_value: "",
              value_type: "llm_prompt",
              required: true,
            },
            {
              id: "new_path",
              type: "string",
              description: "The new file or folder path (e.g., 'src/components/NewButton.tsx'). Must include the full path with file extension.",
              dynamic_variable: "",
              constant_value: "",
              value_type: "llm_prompt",
              required: true,
            },
            {
              id: "project_id",
              type: "string",
              description: "The project ID",
              dynamic_variable: "",
              constant_value: "68c9f40a002d5afe6b43",
              value_type: "constant",
              required: true,
            },
          ],
          dynamic_variable: "",
          constant_value: "",
          value_type: "llm_prompt",
        },
        request_headers: [],
        auth_connection: null,
      },
      response_timeout_secs: 20,
      assignments: [],
      disable_interruptions: false,
      force_pre_tool_speech: "auto",
      tool_call_sound: null,
      tool_call_sound_behavior: "auto",
      execution_mode: "immediate",
      dynamic_variables: {
        dynamic_variable_placeholders: {},
      },
    },
  },
  {
    id: "4",
    name: "Get Project Files",
    description: "Get a list of all files in the project or read a specific file's content",
    filename: "tool4_get_project_files.json",
    config: {
      type: "webhook",
      name: "get_project_files",
      description: "Get a list of all files in the project or read a specific file's content. Use this to understand the existing codebase before making changes. Always check existing files before modifying them to preserve existing code and imports.",
      api_schema: {
        url: "https://code-easy-gamma.vercel.app/api/files",
        method: "GET",
        path_params_schema: [],
        query_params_schema: [
          {
            id: "projectId",
            type: "string",
            description: "The project ID",
            dynamic_variable: "",
            constant_value: "68c9f40a002d5afe6b43",
            value_type: "constant",
            required: true,
          },
          {
            id: "path",
            type: "string",
            description: "Optional: Specific file path to read. If omitted, returns all files in the project.",
            dynamic_variable: "",
            constant_value: "",
            value_type: "llm_prompt",
            required: false,
          },
        ],
        request_body_schema: null,
        request_headers: [],
        auth_connection: null,
      },
      response_timeout_secs: 20,
      assignments: [],
      disable_interruptions: false,
      force_pre_tool_speech: "auto",
      tool_call_sound: null,
      tool_call_sound_behavior: "auto",
      execution_mode: "immediate",
      dynamic_variables: {
        dynamic_variable_placeholders: {},
      },
    },
  },
  {
    id: "5",
    name: "Generate Code with Context",
    description: "Intelligently generate or modify code based on user's request with full project context",
    filename: "tool_code_generation.json",
    config: {
      type: "webhook",
      name: "generate_code_with_context",
      description: "Intelligently generate or modify code based on user's request. This tool analyzes the project context, identifies relevant files, formulates a plan, and generates complete working code. Use this for any code generation task - it will automatically find and update the right files.",
      api_schema: {
        url: "https://code-easy-gamma.vercel.app/api/webhooks/elevenlabs/code-generation",
        method: "POST",
        path_params_schema: [],
        query_params_schema: [],
        request_body_schema: {
          id: "body",
          type: "object",
          description: "The request body containing code generation details",
          required: true,
          properties: [
            {
              id: "user_request",
              type: "string",
              description: "The user's coding request or task description. Be specific about what code needs to be generated or modified.",
              dynamic_variable: "",
              constant_value: "",
              value_type: "llm_prompt",
              required: true,
            },
            {
              id: "project_id",
              type: "string",
              description: "The project ID. Use the value from the conversation context or userId.",
              dynamic_variable: "",
              constant_value: "68c9f40a002d5afe6b43",
              value_type: "constant",
              required: true,
            },
          ],
          dynamic_variable: "",
          constant_value: "",
          value_type: "llm_prompt",
        },
        request_headers: [],
        auth_connection: null,
      },
      response_timeout_secs: 60,
      assignments: [],
      disable_interruptions: false,
      force_pre_tool_speech: false,
      tool_call_sound: null,
      tool_call_sound_behavior: "auto",
      execution_mode: "immediate",
      dynamic_variables: {
        dynamic_variable_placeholders: {},
      },
    },
  },
  {
    id: "6",
    name: "Generate Code (Client Tool)",
    description: "Generate code using AI - Returns code data to agent for use with file tools",
    filename: "tool6_generate_code_client.json",
    config: {
      type: "client",
      name: "generateCode",
      description: "Generate clean, production-ready code based on user requirements. This tool returns structured code data that must then be used with createFile or updateFile to actually save the code. Always use this tool first when the user requests code generation, then use the returned code with file management tools.",
      expects_response: true,
      response_timeout_secs: 60,
      parameters: [
        {
          data_type: "string",
          identifier: "request",
          required: true,
          description: "The code generation request with specific requirements. Be detailed and clear about what code needs to be generated (e.g., 'Create a React button component with variant and size props', 'Add error handling to the login function').",
        },
        {
          data_type: "string",
          identifier: "language",
          required: true,
          description: "Programming language for the code to be generated. Examples: 'javascript', 'typescript', 'python', 'html', 'css', 'react', 'typescript' (for .tsx files).",
        },
        {
          data_type: "string",
          identifier: "context",
          required: false,
          description: "Additional context about the project, existing code, or requirements. Include information about the tech stack, framework, or specific patterns to follow.",
        },
      ],
      dynamic_variables: {
        dynamic_variable_placeholders: {},
      },
      assignments: [],
      disable_interruptions: false,
      force_pre_tool_speech: false,
      tool_call_sound: null,
      tool_call_sound_behavior: "auto",
      execution_mode: "immediate",
    },
  },
  {
    id: "7",
    name: "Create File (Client Tool)",
    description: "Create a new file with the provided content",
    filename: "tool7_create_file_client.json",
    config: {
      type: "client",
      name: "createFile",
      description: "Create a new file in the project with the provided content. Use this after generating code with generateCode tool. Always provide the complete file path including directory structure (e.g., 'src/components/Button.tsx').",
      expects_response: true,
      response_timeout_secs: 30,
      parameters: [
        {
          data_type: "string",
          identifier: "filename",
          required: true,
          description: "The complete file path relative to project root, including directory structure and file extension (e.g., 'src/components/Login.tsx', 'utils/helpers.js', 'styles/global.css').",
        },
        {
          data_type: "string",
          identifier: "content",
          required: true,
          description: "The complete file content including all code, imports, comments, and necessary boilerplate. This must be the full, working code - not a snippet or partial code.",
        },
      ],
      dynamic_variables: {
        dynamic_variable_placeholders: {},
      },
      assignments: [],
      disable_interruptions: false,
      force_pre_tool_speech: false,
      tool_call_sound: null,
      tool_call_sound_behavior: "auto",
      execution_mode: "immediate",
    },
  },
  {
    id: "8",
    name: "Update File (Client Tool)",
    description: "Update an existing file with new content",
    filename: "tool8_update_file_client.json",
    config: {
      type: "client",
      name: "updateFile",
      description: "Update an existing file in the project with new content. Use this after generating code with generateCode tool. Always provide the complete updated file content (merge existing code with new changes).",
      expects_response: true,
      response_timeout_secs: 30,
      parameters: [
        {
          data_type: "string",
          identifier: "filename",
          required: true,
          description: "The complete file path relative to project root, including directory structure and file extension (e.g., 'src/components/Login.tsx').",
        },
        {
          data_type: "string",
          identifier: "content",
          required: true,
          description: "The complete updated file content. This must include ALL existing code plus your changes - merge, don't replace. Include all imports, existing functions, and new code together.",
        },
      ],
      dynamic_variables: {
        dynamic_variable_placeholders: {},
      },
      assignments: [],
      disable_interruptions: false,
      force_pre_tool_speech: false,
      tool_call_sound: null,
      tool_call_sound_behavior: "auto",
      execution_mode: "immediate",
    },
  },
  {
    id: "9",
    name: "Delete File (Client Tool)",
    description: "Delete a file from the project",
    filename: "tool9_delete_file_client.json",
    config: {
      type: "client",
      name: "deleteFile",
      description: "Delete a file from the project. Use this when the user wants to remove a file or clean up the project structure.",
      expects_response: true,
      response_timeout_secs: 20,
      parameters: [
        {
          data_type: "string",
          identifier: "filename",
          required: true,
          description: "The complete file path relative to project root to delete (e.g., 'src/components/OldComponent.tsx').",
        },
      ],
      dynamic_variables: {
        dynamic_variable_placeholders: {},
      },
      assignments: [],
      disable_interruptions: false,
      force_pre_tool_speech: false,
      tool_call_sound: null,
      tool_call_sound_behavior: "auto",
      execution_mode: "immediate",
    },
  },
  {
    id: "10",
    name: "Get Project Files (Client Tool)",
    description: "Get list of all files or read a specific file's content",
    filename: "tool10_get_project_files_client.json",
    config: {
      type: "client",
      name: "getProjectFiles",
      description: "Get a list of all files in the project or read a specific file's content. Use this to understand the existing codebase before making changes. Always check existing files before modifying them to preserve existing code and imports.",
      expects_response: true,
      response_timeout_secs: 20,
      parameters: [
        {
          data_type: "string",
          identifier: "path",
          required: false,
          description: "Optional: Specific file path to read. If omitted or empty, returns all files in the project. Include full path with extension (e.g., 'src/components/Login.tsx').",
        },
      ],
      dynamic_variables: {
        dynamic_variable_placeholders: {},
      },
      assignments: [],
      disable_interruptions: false,
      force_pre_tool_speech: false,
      tool_call_sound: null,
      tool_call_sound_behavior: "auto",
      execution_mode: "immediate",
    },
  },
  {
    id: "builder-1",
    name: "Check Auth (Builder)",
    description: "Verify user authentication before executing builder operations",
    filename: "tool_builder_check_auth.json",
    config: {
      type: "webhook",
      name: "check_auth_builder",
      description: "Verify that the user is authenticated before executing any builder-specific operations. Use this tool first before scaffolding, building, or modifying builder projects.",
      api_schema: {
        url: "https://code-easy-gamma.vercel.app/api/builder/auth-check",
        method: "POST",
        path_params_schema: [],
        query_params_schema: null,
        request_body_schema: {
          id: "body",
          type: "object",
          description: "The request body containing session token",
          required: true,
          properties: [
            {
              id: "sessionToken",
              type: "string",
              description: "The user's session token for authentication",
              dynamic_variable: "user_session_token",
              constant_value: "",
              value_type: "dynamic_variable",
              required: true,
            },
          ],
          dynamic_variable: "",
          constant_value: "",
          value_type: "llm_prompt",
        },
        request_headers: [],
        auth_connection: null,
      },
      response_timeout_secs: 10,
      assignments: [],
      disable_interruptions: false,
      force_pre_tool_speech: "auto",
      tool_call_sound: null,
      tool_call_sound_behavior: "auto",
      execution_mode: "immediate",
      dynamic_variables: {
        dynamic_variable_placeholders: {},
      },
    },
  },
  {
    id: "builder-2",
    name: "Scaffold Project (Builder)",
    description: "Create a new framework project using scaffolding tools",
    filename: "tool_builder_scaffold.json",
    config: {
      type: "webhook",
      name: "scaffold_project",
      description: "Scaffold a new framework project (Next.js, React, Vue, Angular, or Svelte). This creates the initial project structure with all necessary files and dependencies. Use this when starting a new builder project.",
      api_schema: {
        url: "https://code-easy-gamma.vercel.app/api/builder/scaffold",
        method: "POST",
        path_params_schema: [],
        query_params_schema: null,
        request_body_schema: {
          id: "body",
          type: "object",
          description: "The request body containing project scaffolding details",
          required: true,
          properties: [
            {
              id: "projectId",
              type: "string",
              description: "The builder project ID to scaffold",
              dynamic_variable: "",
              constant_value: "",
              value_type: "llm_prompt",
              required: true,
            },
            {
              id: "description",
              type: "string",
              description: "Optional: Description of what the project should be",
              dynamic_variable: "",
              constant_value: "",
              value_type: "llm_prompt",
              required: false,
            },
          ],
          dynamic_variable: "",
          constant_value: "",
          value_type: "llm_prompt",
        },
        request_headers: [
          {
            id: "Authorization",
            type: "string",
            description: "Bearer token for authentication",
            dynamic_variable: "user_session_token",
            constant_value: "",
            value_type: "dynamic_variable",
            required: true,
          },
        ],
        auth_connection: null,
      },
      response_timeout_secs: 120, // Max 120 seconds (ElevenLabs limit) - scaffolding may take longer but will timeout
      assignments: [],
      disable_interruptions: false,
      force_pre_tool_speech: "auto",
      tool_call_sound: null,
      tool_call_sound_behavior: "auto",
      execution_mode: "immediate",
      dynamic_variables: {
        dynamic_variable_placeholders: {},
      },
    },
  },
  {
    id: "builder-3",
    name: "Install Dependencies (Builder)",
    description: "Install npm packages in a builder project",
    filename: "tool_builder_install_dependencies.json",
    config: {
      type: "webhook",
      name: "install_dependencies",
      description: "Install npm packages in a builder project. Use this when the project needs additional dependencies or packages to be installed. Provide a comma-separated list of package names.",
      api_schema: {
        url: "https://code-easy-gamma.vercel.app/api/builder/dependencies",
        method: "POST",
        path_params_schema: [],
        query_params_schema: null,
        request_body_schema: {
          id: "body",
          type: "object",
          description: "The request body containing dependency installation details",
          required: true,
          properties: [
            {
              id: "projectId",
              type: "string",
              description: "The builder project ID",
              dynamic_variable: "",
              constant_value: "",
              value_type: "llm_prompt",
              required: true,
            },
            {
              id: "packages",
              type: "string",
              description: "Comma-separated list of package names to install (e.g., 'lodash,axios,date-fns')",
              dynamic_variable: "",
              constant_value: "",
              value_type: "llm_prompt",
              required: true,
            },
            {
              id: "dev",
              type: "boolean",
              description: "Whether to install as dev dependencies. Defaults to false.",
              dynamic_variable: "",
              constant_value: "",
              value_type: "llm_prompt",
              required: false,
            },
          ],
          dynamic_variable: "",
          constant_value: "",
          value_type: "llm_prompt",
        },
        request_headers: [
          {
            id: "Authorization",
            type: "string",
            description: "Bearer token for authentication",
            dynamic_variable: "user_session_token",
            constant_value: "",
            value_type: "dynamic_variable",
            required: true,
          },
        ],
        auth_connection: null,
      },
      response_timeout_secs: 120, // Max 120 seconds (ElevenLabs limit) - installation may take longer but will timeout
      assignments: [],
      disable_interruptions: false,
      force_pre_tool_speech: "auto",
      tool_call_sound: null,
      tool_call_sound_behavior: "auto",
      execution_mode: "immediate",
      dynamic_variables: {
        dynamic_variable_placeholders: {},
      },
    },
  },
  {
    id: "builder-4",
    name: "Run Build (Builder)",
    description: "Build a builder project for production",
    filename: "tool_builder_run_build.json",
    config: {
      type: "webhook",
      name: "run_build",
      description: "Build a builder project for production. This compiles and optimizes the project. Use this when the project is ready to be built or when the user requests a build.",
      api_schema: {
        url: "https://code-easy-gamma.vercel.app/api/builder/build",
        method: "POST",
        path_params_schema: [],
        query_params_schema: null,
        request_body_schema: {
          id: "body",
          type: "object",
          description: "The request body containing build details",
          required: true,
          properties: [
            {
              id: "projectId",
              type: "string",
              description: "The builder project ID to build",
              dynamic_variable: "",
              constant_value: "",
              value_type: "llm_prompt",
              required: true,
            },
          ],
          dynamic_variable: "",
          constant_value: "",
          value_type: "llm_prompt",
        },
        request_headers: [
          {
            id: "Authorization",
            type: "string",
            description: "Bearer token for authentication",
            dynamic_variable: "user_session_token",
            constant_value: "",
            value_type: "dynamic_variable",
            required: true,
          },
        ],
        auth_connection: null,
      },
      response_timeout_secs: 120, // Max 120 seconds (ElevenLabs limit) - build may take longer but will timeout
      assignments: [],
      disable_interruptions: false,
      force_pre_tool_speech: "auto",
      tool_call_sound: null,
      tool_call_sound_behavior: "auto",
      execution_mode: "immediate",
      dynamic_variables: {
        dynamic_variable_placeholders: {},
      },
    },
  },
  {
    id: "builder-5",
    name: "Start Preview Server (Builder)",
    description: "Start a preview server for a builder project",
    filename: "tool_builder_start_preview.json",
    config: {
      type: "webhook",
      name: "start_preview_server",
      description: "Start a development preview server for a builder project. This allows the user to see the app running live. The server will be accessible via a preview URL that will be returned.",
      api_schema: {
        url: "https://code-easy-gamma.vercel.app/api/builder/preview/start",
        method: "POST",
        path_params_schema: [],
        query_params_schema: null,
        request_body_schema: {
          id: "body",
          type: "object",
          description: "The request body containing preview server details",
          required: true,
          properties: [
            {
              id: "projectId",
              type: "string",
              description: "The builder project ID to start preview for",
              dynamic_variable: "",
              constant_value: "",
              value_type: "llm_prompt",
              required: true,
            },
          ],
          dynamic_variable: "",
          constant_value: "",
          value_type: "llm_prompt",
        },
        request_headers: [
          {
            id: "Authorization",
            type: "string",
            description: "Bearer token for authentication",
            dynamic_variable: "user_session_token",
            constant_value: "",
            value_type: "dynamic_variable",
            required: true,
          },
        ],
        auth_connection: null,
      },
      response_timeout_secs: 60,
      assignments: [],
      disable_interruptions: false,
      force_pre_tool_speech: "auto",
      tool_call_sound: null,
      tool_call_sound_behavior: "auto",
      execution_mode: "immediate",
      dynamic_variables: {
        dynamic_variable_placeholders: {},
      },
    },
  },
] as const;

